"""
Code Sanitizer Module
=====================
Handles cleaning and validation of LLM-generated code.

CRITICAL PURPOSE:
The LLM may accidentally include markdown formatting (```python), 
explanatory text, or other non-code content. This module strips
all formatting to produce clean, executable code.

WHY THIS MATTERS:
- Prevents syntax errors from markdown wrappers
- Removes potentially harmful explanatory text
- Ensures only valid code reaches the executor
"""

import re
from typing import Optional, Tuple


class CodeSanitizer:
    """
    Sanitizes and validates code generated by the LLM.
    
    This class provides methods to:
    1. Strip markdown code blocks
    2. Remove comments that might interfere with execution
    3. Validate that code appears to be valid Python/shell
    4. Detect and handle common LLM output issues
    """
    
    # Regex patterns for markdown code blocks
    MARKDOWN_PATTERNS = [
        r'```python\s*\n(.*?)\n```',      # ```python ... ```
        r'```py\s*\n(.*?)\n```',          # ```py ... ```
        r'```bash\s*\n(.*?)\n```',        # ```bash ... ```
        r'```sh\s*\n(.*?)\n```',          # ```sh ... ```
        r'```shell\s*\n(.*?)\n```',       # ```shell ... ```
        r'```powershell\s*\n(.*?)\n```',  # ```powershell ... ```
        r'```\s*\n(.*?)\n```',            # Generic ``` ... ```
    ]
    
    # Patterns to detect non-code content
    EXPLANATORY_PATTERNS = [
        r'^\s*(here|this)\s+(is|will|shows?)\s+',  # "Here is the code"
        r'^\s*i\s+(hope|think|believe)\s+',         # "I hope this helps"
        r'^\s*let\s+me\s+',                         # "Let me help you"
        r'^\s*sure[,!]',                            # "Sure, here's..."
        r'^\s*certainly[,!]',                       # "Certainly, ..."
    ]
    
    def __init__(self, max_length: int = 50000):
        """
        Initialize the CodeSanitizer.
        
        Args:
            max_length: Maximum allowed code length in characters
        """
        self.max_length = max_length
        self.warnings = []  # Store warnings about the code
    
    def sanitize(self, code: str, script_type: str = 'python') -> str:
        """
        Main sanitization method - cleans code for execution.
        
        This method:
        1. Strips markdown wrappers
        2. Removes explanatory text
        3. Trims whitespace
        4. Validates length
        
        Args:
            code: Raw code string from LLM
            script_type: Type of script ('python', 'bash', 'powershell')
            
        Returns:
            str: Cleaned, executable code
        """
        self.warnings = []  # Reset warnings
        
        if not code or not code.strip():
            raise ValueError("Generated code is empty")
        
        # Step 1: Strip markdown code blocks
        code = self._strip_markdown(code, script_type)
        
        # Step 2: Remove common explanatory phrases
        code = self._remove_explanatory_text(code)
        
        # Step 3: Trim leading/trailing whitespace
        code = code.strip()
        
        # Step 4: Validate length
        if len(code) > self.max_length:
            self.warnings.append(
                f"Code exceeds maximum length ({len(code)}/{self.max_length} chars)"
            )
            code = code[:self.max_length]
        
        # Step 5: Validate code appears valid
        self._validate_code(code, script_type)
        
        return code
    
    def _strip_markdown(self, code: str, script_type: str = 'python') -> str:
        """
        Remove markdown code block wrappers.
        
        Tries to match specific language markers first (```python),
        then falls back to generic markers (```).
        
        Args:
            code: Code potentially containing markdown
            script_type: Expected script type for better matching
            
        Returns:
            str: Code without markdown wrappers
        """
        original_code = code
        
        # Try to find and extract code from markdown blocks
        # First, try language-specific patterns
        lang_map = {
            'python': ['python', 'py'],
            'bash': ['bash', 'sh', 'shell'],
            'powershell': ['powershell', 'ps1'],
        }
        
        # Get relevant patterns for this script type
        specific_patterns = []
        if script_type in lang_map:
            for lang in lang_map[script_type]:
                pattern = f'```{lang}\\s*\\n(.*?)\\n```'
                match = re.search(pattern, code, re.DOTALL | re.IGNORECASE)
                if match:
                    return match.group(1).strip()
        
        # Fall back to generic pattern (any ``` block)
        generic_pattern = r'```\s*\n(.*?)\n```'
        match = re.search(generic_pattern, code, re.DOTALL)
        if match:
            return match.group(1).strip()
        
        # No markdown found, return as-is
        return code
    
    def _remove_explanatory_text(self, code: str) -> str:
        """
        Remove common explanatory phrases that LLMs add.
        
        This handles cases where the LLM outputs text like:
        "Here's the code you requested:" before the actual code.
        
        Args:
            code: Code potentially containing explanatory text
            
        Returns:
            str: Code with explanatory text removed
        """
        lines = code.split('\n')
        cleaned_lines = []
        skip_until_code = False
        
        for line in lines:
            stripped = line.strip()
            
            # Check if this line matches explanatory patterns
            is_explanatory = False
            for pattern in self.EXPLANATORY_PATTERNS:
                if re.match(pattern, stripped, re.IGNORECASE):
                    is_explanatory = True
                    self.warnings.append(f"Removed explanatory line: '{stripped[:50]}...'")
                    break
            
            # Skip explanatory lines
            if not is_explanatory and stripped:
                cleaned_lines.append(line)
            elif stripped:
                # Log that we removed it
                pass
        
        return '\n'.join(cleaned_lines)
    
    def _validate_code(self, code: str, script_type: str) -> None:
        """
        Perform basic validation on the code.
        
        This doesn't guarantee the code will work, but checks
        for obvious issues like empty code or syntax errors.
        
        Args:
            code: Sanitized code to validate
            script_type: Type of script
            
        Raises:
            ValueError: If code fails validation
        """
        if not code.strip():
            raise ValueError("Code is empty after sanitization")
        
        # Python-specific validation
        if script_type == 'python':
            # Check for basic Python syntax indicators
            has_python_indicators = any([
                'import ' in code,
                'def ' in code,
                'class ' in code,
                'print(' in code,
                'if __name__' in code,
                '=' in code,  # Assignment
            ])
            
            # If no indicators, warn but don't fail
            if not has_python_indicators:
                self.warnings.append(
                    "Code may not be valid Python - no common Python syntax detected"
                )
        
        # Bash/PowerShell validation
        elif script_type in ['bash', 'powershell']:
            # Check for shell script indicators
            has_shell_indicators = any([
                'echo ' in code,
                'ls ' in code,
                'cd ' in code,
                'rm ' in code,
                '$' in code,  # Variables
                '|' in code,  # Pipes
            ])
            
            if not has_shell_indicators:
                self.warnings.append(
                    f"Code may not be valid {script_type} - no common shell syntax detected"
                )
    
    def get_warnings(self) -> list:
        """
        Get list of warnings generated during sanitization.
        
        Returns:
            list: List of warning strings
        """
        return self.warnings.copy()
    
    def detect_script_type(self, code: str) -> str:
        """
        Auto-detect the type of script based on code content.
        
        Args:
            code: Code to analyze
            
        Returns:
            str: Detected script type ('python', 'bash', 'powershell')
        """
        code_lower = code.lower()
        
        # Python indicators
        python_score = sum([
            'import ' in code,
            'def ' in code,
            'print(' in code,
            'if __name__' in code,
            'self.' in code,
        ])
        
        # PowerShell indicators
        powershell_score = sum([
            'powershell' in code_lower,
            '$' in code and '=' in code,
            'Write-Host' in code,
            'Get-ChildItem' in code,
            'Invoke-' in code,
        ])
        
        # Bash indicators
        bash_score = sum([
            '#!/bin/bash' in code,
            'echo ' in code,
            'ls ' in code,
            '| ' in code and '>' in code,
        ])
        
        scores = {
            'python': python_score,
            'powershell': powershell_score,
            'bash': bash_score,
        }
        
        # Return highest scoring type
        return max(scores, key=scores.get) if any(scores.values()) else 'python'


# Convenience function
def sanitize_code(code: str, script_type: str = 'python') -> Tuple[str, list]:
    """
    Quick sanitization function.
    
    Args:
        code: Raw code from LLM
        script_type: Expected script type
        
    Returns:
        Tuple of (sanitized_code, warnings_list)
    """
    sanitizer = CodeSanitizer()
    sanitized = sanitizer.sanitize(code, script_type)
    return sanitized, sanitizer.get_warnings()
